public class Resolve {
	public static void main(String[] args) {
		System.out.println("This is an autogenerated mail");
		System.out.println("Monday Morning, I will be available");
		System.out.println("We will discuss");

	}

}
